version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:16.1
    ports:
      -  "5432:5432"
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=${POSTGRES_USER:-postgres}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}"
      - "POSTGRES_DB=${POSTGRES_DB:-postgres}"

volumes:
  postgres-data: